<h1><?php echo $this->__('Logs') ?></h1>
<table class="table">
    <thead>
    <tr>
        <th width="1"><?php echo $this->__('Date') ?></th>
        <th><?php echo $this->__('Author') ?></th>
        <th><?php echo $this->__('Message') ?></th>
        <th width="1"><?php echo $this->__('Status') ?></th>
        <th width="1">&nbsp;</th>
    </tr>
    </thead>
    <tbody>
    <?php
    foreach($this->logs as $row) {
        ?>
        <tr>
            <td><span class="badge"><?php echo $row['date'] ?></span></td>
            <td><?php echo $row['author'] ?></td>
            <td>
                <?php
                echo $row['message'];
                if(isset($row['files'])) {
                    $files = explode(',', $row['files']);
                    ?>
                    <br />
                    <small>
                        <a href="javascript:;" onclick="$('#files-<?php echo $row['id'] ?>').toggle()"><?php echo $this->__('Show files') ?></a>
                        <pre id="files-<?php echo $row['id'] ?>" style="display: none"><?php echo implode(PHP_EOL, explode(',', $row['files'])) ?></pre>
                    </small>
                    <?php
                }
                ?>
            </td>
            <td class="text-center"><?php echo $row['status'] == 1 ? '✔' : ($row['status'] == 0 ? '❌' : '') ?></td>
            <td>
                <a href="<?php echo $this->link('logs', ['delete' => $row['id']]) ?>"
                   onclick="return confirm('<?php echo $this->__('Are you sure ?') ?>')"
                   class="btn btn-sm btn-outline-danger"
                ><?php echo $this->__('Delete') ?></a>
            </td>
        </tr>
        <?php
    }
    ?>
    </tbody>
</table>